# Rough Work

In [ ]:
import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])


In [ ]:
temp = m2.T

In [ ]:
temp

array([[5, 7],
       [6, 8]])

In [ ]:
np.roll(temp, 1)

array([[8, 5],
       [7, 6]])

# Min Max

In [ ]:
# Min Max

import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
temp = m2.T
print(f"Matrix 1 : \n{m1}\n\nMatrix2 : \n{m2}\n\nTranspose of Matrix 2 : \n{temp}")
final = []
for i in m1:
  c=[]
  for j in temp:
    c.append(np.min(np.maximum(i ,j)))
  final.append(c)
final = np.array(final)
final

array([[5, 6],
       [5, 6]])

# Min Product

In [ ]:
# Min Prod

import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
temp = m2.T
print(f"Matrix 1 : \n{m1}\n\nMatrix2 : \n{m2}\n\nTranspose of Matrix 2 : \n{temp}")
final = []
# for i in m1:
#   c=[]
#   for j in temp:
#     c.append(np.min(np.multiply(i ,j)))
#   final.append(c)
final = np.min(np.multiply(m1[:, np.newaxis], temp), axis=2)
final = np.array(final)
final

Matrix 1 : 
[[1 2]
 [3 4]]

Matrix2 : 
[[5 6]
 [7 8]]

Transpose of Matrix 2 : 
[[5 7]
 [6 8]]


array([[ 5,  6],
       [15, 18]])

In [ ]:
m1[:, np.newaxis]

array([[[1, 2]],

       [[3, 4]]])

In [ ]:
np.maximum(m1[:, np.newaxis], temp)

array([[[5, 7],
        [6, 8]],

       [[5, 7],
        [6, 8]]])